ui: tape
browsers:
  - name: android
    version: latest
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: internet explorer
    version: latest
  - name: ipad
    version: latest
  - name: iphone
    version: latest
  - name: microsoftedge
    version: latest
  - name: opera
    version: latest
  - name: safari
    version: latest
