ui: tape
browsers:
  - name: chrome
    version: 26
  - name: firefox
    version: 4
  - name: internet explorer
    version: 9
  - name: iphone
    version: 8.1
  - name: microsoftedge
    version: 13
  - name: opera
    version: 11
  - name: safari
    version: 6
